# Generated by go2rpm 1.13.0.post0
%bcond_without check
%global debug_package %{nil}

# https://github.com/mautrix/go
%global goipath         maunium.net/go/mautrix
%global forgeurl        https://github.com/mautrix/go
Version:                0.18.1

%gometa -L -f

%global common_description %{expand:
A Golang Matrix framework.}

%global golicenses      LICENSE
%global godocs          example CHANGELOG.md README.md
%global gosupfiles      {00..14}-*.sql

Name:           golang-maunium-mautrix-skoved
Release:        %autorelease
Summary:        A Golang Matrix framework

License:        MPL-2.0 AND MIT AND Apache-2.0
URL:            %{gourl}
Source:         %{gosource}
Patch1:         0001-Unvendor-crypto-canonicaljson.patch

BuildRequires: gcc-c++
BuildRequires: libolm-devel

Provides:      bundled(golang(codeberg.org/DerLukas/goolm)) = 0.2.3
Provides:      bundled(golang(github.com/Dhole/go-olm)) = 0
Provides:      bundled(golang(github.com/zyedidia/glob)) = 0

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
