# Generated by go2rpm 1.16.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/mautrix/discord
%global goipath         go.mau.fi/mautrix-discord
%global forgeurl        https://github.com/mautrix/discord
Version:                0.7.3
%global tag             v0.7.3
%global commit          001c88c

%global buildtime       %(date '+%%b %%_d %%Y, %%H:%%M:%%S')

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global common_description %{expand:
A Matrix-Discord puppeting bridge based on discordgo.}

%global golicenses      LICENSE
%global godocs          CHANGELOG.md README.md ROADMAP.md\\\
                        remoteauth/README.md

Name:           mautrix-discord
Release:        %autorelease
Summary:        A Matrix-Discord puppeting bridge

License:        AGPL-3.0-only
URL:            %{gourl}
Source:         %{gosource}

Requires:       libolm
BuildRequires:  libolm
BuildRequires:  libolm-devel

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
export LDFLAGS="-X main.Tag=%{name} -X main.Commit=%{commit} -X 'main.BuildTime=%{buildtime}'"
%gobuild -o %{gobuilddir}/bin/%{name} %{goipath}
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
install -m 0755 -vd                     %{buildroot}%{_pkgdocdir}
install -m 0644 -vp example-config.yaml %{buildroot}%{_pkgdocdir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE
%dir %{_pkgdocdir}
%doc CHANGELOG.md README.md ROADMAP.md remoteauth/README.md %{_pkgdocdir}/example-config.yaml
%{_bindir}/%{name}
%endif

%gopkgfiles

%changelog
%autochangelog
