# Generated by go2rpm 1.16.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/bwmarrin/discordgo
%global goipath         github.com/bwmarrin/discordgo
Version:                0.27.0
%global tag             v0.27.0

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global common_description %{expand:
DiscordGo is a Go package that provides low level bindings to the Discord chat
client API. DiscordGo has nearly complete support for all of the Discord API
endpoints, websocket interface, and voice interface.}

%global golicenses      LICENSE
%global godocs          docs examples CONTRIBUTING.md README.md

Name:           golang-github-bwmarrin-discordgo
Release:        %autorelease
Summary:        (Golang) Go bindings for Discord

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}
# add format string to restapi.go:299 to make go vet's printf analyzer happy during testing
# See:
# https://github.com/bwmarrin/discordgo/issues/1630
# and
# https://github.com/bwmarrin/discordgo/pull/1631
Patch:          01-fix-sprintf.patch

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1
# we don't need to package the examples
rm -r examples

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%gopkgfiles

%changelog
%autochangelog
